// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaigxPIqrEpGBjewIcX3m7PJkXbUL5ZAw',
    appId: '1:229949640440:web:8c92d2e85a06b5c953b50d',
    messagingSenderId: '229949640440',
    projectId: 'aiproject-e79aa',
    authDomain: 'aiproject-e79aa.firebaseapp.com',
    storageBucket: 'aiproject-e79aa.appspot.com',
    measurementId: 'G-VMPJSCPG5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-UwN_EOvnxQvLFbiN2b0E6wtLQ2Q1xjY',
    appId: '1:229949640440:android:3921ee8e24471ef353b50d',
    messagingSenderId: '229949640440',
    projectId: 'aiproject-e79aa',
    storageBucket: 'aiproject-e79aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKQI8FImIUgjAY7O6Wwp_K-io5SbKFbX4',
    appId: '1:229949640440:ios:88a9bc955c63711b53b50d',
    messagingSenderId: '229949640440',
    projectId: 'aiproject-e79aa',
    storageBucket: 'aiproject-e79aa.appspot.com',
    iosBundleId: 'com.example.aiPlaygroundProject',
  );
}
